name: Automated tests ProrabTech

on:
    push

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout repository
            uses: actions/checkout@v4
          - name: setup Python
            uses: actions/setup-python@v5
            with:
                python-version: "3.14"
          - name: Install Chrome
            run: sudo apt-get install google-chrome-stable
          - name: install dependencies
            run: pip install -r requirements.txt
          - name: Run tests
            env:
                LOGIN: ${{ secrets.LOGIN }}
                PASSWORD: ${{ secrets.PASSWORD }}
            run: pytest
